/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.ConnexionBDD;
import Entity.FonctionMetier;
import Model.ModelMedicament;
import static java.lang.Float.parseFloat;

/**
 *
 * @author fello
 */
public class frmInteraction1 extends javax.swing.JFrame {
    
     ModelMedicament mdlMedicament;
     ModelMedicament mdlMedicament2;
    FonctionMetier fm;

    /**
     * Creates new form frmInteraction
     */
    public frmInteraction1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedPerturber = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListeAllMed = new javax.swing.JTable();
        btnInteragir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMedNonPerturber = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblMedPerturber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Depot legal", "Médicament perturber"
            }
        ));
        jScrollPane1.setViewportView(tblMedPerturber);

        tblListeAllMed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Depot legal", "Nom Médicament"
            }
        ));
        tblListeAllMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListeAllMedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListeAllMed);

        btnInteragir.setText("ajouter interaction");
        btnInteragir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInteragirMouseClicked(evt);
            }
        });

        tblMedNonPerturber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Depot legal", "Médicament non concérné"
            }
        ));
        jScrollPane3.setViewportView(tblMedNonPerturber);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnInteragir, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnInteragir)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
         // TODO add your handling code here:
        ConnexionBDD cnx = new ConnexionBDD() ;
        // On crée notre objet FonctionsMetier
        fm = new FonctionMetier();
        // On crée notre modelJeux
        mdlMedicament = new ModelMedicament();
        // On charge les données dans le modèle
        mdlMedicament.loadDatas2Colonnes(fm.getAllMedicaments());
        // On met à jour le modèle du JTable
        tblListeAllMed.setModel(mdlMedicament);
        // On remplit la ComboBox avec le nom des catégories
//        for (Medicament med : fm.getAllMedicaments())
//        {
//            cboCategorie.addItem(med.getNomCommercial());
//        }
        // On affiche le prochain numéro du jeu
//        txtIdJeux.setText(String.valueOf(fm.getLastIdJeu()));
        
    }//GEN-LAST:event_formWindowOpened

    private void tblListeAllMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListeAllMedMouseClicked
        // TODO add your handling code here:
           // TODO add your handling code here:
        ConnexionBDD cnx = new ConnexionBDD() ;
        // On crée notre objet FonctionsMetier
        fm = new FonctionMetier();
        // On crée notre modelJeux
        mdlMedicament = new ModelMedicament();
        // On charge les données dans le modèle
        
        int numMedoc = Integer.parseInt(tblListeAllMed.getValueAt(tblListeAllMed.getSelectedRow(), 0).toString());
        
        mdlMedicament.loadDatas2Colonnes(fm.getAllMedicamentsPerturber(numMedoc));
        // On met à jour le modèle du JTable
        tblMedPerturber.setModel(mdlMedicament);
        
        mdlMedicament2 = new ModelMedicament();
        mdlMedicament2.loadDatas2Colonnes(fm.getAllMedicamentsNonPerturber(numMedoc));
        tblMedNonPerturber.setModel(mdlMedicament2);
        
        // On remplit la ComboBox avec le nom des catégories
//        for (Medicament med : fm.getAllMedicaments())
//        {
//            cboCategorie.addItem(med.getNomCommercial());
//        }
        // On affiche le prochain numéro du jeu
//        txtIdJeux.setText(String.valueOf(fm.getLastIdJeu()));
    }//GEN-LAST:event_tblListeAllMedMouseClicked

    private void btnInteragirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInteragirMouseClicked
        // TODO add your handling code here:
        int numMedocPerturbateur = Integer.parseInt(tblMedNonPerturber.getValueAt(tblMedNonPerturber.getSelectedRow(), 0).toString());
        int numMedocperturber = Integer.parseInt(tblListeAllMed.getValueAt(tblListeAllMed.getSelectedRow(), 0).toString());
        
        
        fm.InsererInteraction(numMedocPerturbateur, numMedocperturber);
        
        
        // une fois que la requette a été faite on reactualise les deux tableau
        ConnexionBDD cnx = new ConnexionBDD() ;
        // On crée notre objet FonctionsMetier
        fm = new FonctionMetier();
        // On crée notre modelJeux
        mdlMedicament = new ModelMedicament();
        // On charge les données dans le modèle
        
        int numMedoc = Integer.parseInt(tblListeAllMed.getValueAt(tblListeAllMed.getSelectedRow(), 0).toString());
        
        mdlMedicament.loadDatas2Colonnes(fm.getAllMedicamentsPerturber(numMedoc));
        // On met à jour le modèle du JTable
        tblMedPerturber.setModel(mdlMedicament);
        
        mdlMedicament2 = new ModelMedicament();
        mdlMedicament2.loadDatas2Colonnes(fm.getAllMedicamentsNonPerturber(numMedoc));
        tblMedNonPerturber.setModel(mdlMedicament2);
        
    }//GEN-LAST:event_btnInteragirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInteraction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInteraction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInteraction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInteraction1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInteraction1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInteragir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblListeAllMed;
    private javax.swing.JTable tblMedNonPerturber;
    private javax.swing.JTable tblMedPerturber;
    // End of variables declaration//GEN-END:variables
}
